version: '3'
services:
  web:
    image: uzresk/web
    ports:
      - 80:80
    container_name: web
    depends_on:
      - app
  app:
    image: uzresk/app
    ports:
      - 8080:8080
      - 8009:8009
    container_name: app

