version: '3'
services:
  web:
    image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-handson-web:latest
    ports:
      - 80:80
    logging:
      driver: awslogs
      options: 
        awslogs-group: aws-hands-on
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: web
  app:
    image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-handson-app:latest
    ports:
      - 8080:8080
      - 8009:8009
    logging:
      driver: awslogs
      options: 
        awslogs-group: aws-hands-on
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: app

